tosca_definitions_version: alien_dsl_2_0_0

metadata:
  template_name: org.alien4cloud.kubernetes.topology.master.kubernetes-master-topology
  template_version: 2.1.0
  template_author: alien4cloud

description: |
  Topology of a Kubernetes Master.

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - org.alien4cloud.kubernetes.kubeadm:2.1.0

topology_template:
  description: |
    Deploy a Kubernetes Master.
  node_templates:
    Compute:
      type: tosca.nodes.Compute
      capabilities:
        os:
          properties:
            architecture: "x86_64"
            type: linux
            distribution: centos
        scalable:
          properties:
            min_instances: 1
            max_instances: 1
            default_instances: 1
        endpoint:
          properties:
            secure: true
            protocol: tcp
            network_name: PRIVATE
            initiator: source
    DockerEngine:
      type: org.alien4cloud.kubernetes.kubeadm.nodes.DockerEngine
      requirements:
        - host:
            node: Compute
            capability: tosca.capabilities.Container
            relationship: tosca.relationships.HostedOn
    KubeMaster:
      type: org.alien4cloud.kubernetes.kubeadm.nodes.KubeMaster
      properties:
        component_version: "1.2.1"
      requirements:
        - host:
            node: DockerEngine
            capability: org.alien4cloud.kubernetes.kubeadm.capabilities.DockerHost
            relationship: org.alien4cloud.kubernetes.kubeadm.relationships.HostedOnDocker
