---

- name: Start httpd service
  service:
    name: httpd
    state: started

- name: Check Carbon
  command: /opt/graphite/bin/carbon-cache.py status
  register: carbon
  failed_when: False
  changed_when: False

- name: Start carbon-cache
  command: /opt/graphite/bin/carbon-cache.py start
  when: carbon.stdout.find('pid') == -1

- name: Sleep 10 sec before starting Graphite
  command: "/bin/sleep 30"

- name: Start Graphite server
  shell: nohup /opt/graphite/graphite-server.sh &
