---

- name: Check httpd service exists
  shell: systemctl | grep httpd
  register: httpd_service
  failed_when: False
  changed_when: False

- name: Stop httpd service
  service:
    name: httpd
    state: stopped
  ignore_errors: yes
  when: httpd_service.rc == 0

- name: Check Carbon exists
  stat: path=/opt/graphite/bin/carbon-cache.py
  register: carbon_cmd

- name: Check Carbon status
  command: /opt/graphite/bin/carbon-cache.py status
  register: carbon
  when: carbon_cmd.stat.exists
  failed_when: False

- name: Stop Carbon
  command: /opt/graphite/bin/carbon-cache.py stop
  when: (carbon_cmd.stat.exists) and (carbon.stdout.find('pid') != -1)

- name: Stop Graphite server
  shell: pids=$(ps -ef |grep run-graphite-devel-server |grep -v grep | awk '{print  $2 }'); for l in $pids; do kill -9 $l; done
  failed_when: False
